# 本地配置文件
# Nacos 配置在 bootstrap.yml 中定义

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      config:
        import-check:
          enabled: false  # 禁用 Nacos 配置导入检查
    compatibility-verifier:
      enabled: false  # 禁用 Spring Cloud 兼容性检查
